### ISSUE TITLE
Can't revert /xlbgmset

### ISSUE THREAD

**Issue by Metaknight3** [goaaats/FFXIVQuickLauncher#121]
I am very unsure if this behavior is intentional but using the /xlbgmset command will force the music to never change between locations, instances, or areas beyond the set song. Additionally this change will only be turned when when re-logging, or closing and relaunching the client entirely. There appears to be neither an option for turning off this change, nor an option to find out what bgm id corresponds to what. Parsing through at least 708 numbers for songs isn't exactly desirable when I wish to reset the bgm itself.

**Comment by ff-meli** [comment]
So this could probably use better documentation somewhere, but that behavior is intentional.  This may change, but for now the way to revert your bgm back to the zone default is to enter an invalid id (such as 900).

A list of all known bgm ids mapped to their track names can be found [here](https://docs.google.com/spreadsheets/d/14yjTMHYmuB1m5-aJO8CkMferRT9sNzgasYq02oJENWs/edit#gid=0).

**Comment by goaaats** [comment]
I'll add something to revert it properly and link the list in a more obvious place

**Comment by Aida-Enna** [comment]
Make sure to credit MagowDeath#1763 when you do - He's the one who keeps it updated in the CMTool discord.

![Magow](http://aida.moe/share/t55M.png)

**Comment by Aida-Enna** [comment]
This is fixed in 4.2 and I added the Google Doc with all the BGM IDs to the FAQ.

**Comment by ff-meli** [comment]
For the record, this isn't actually fixed yet (it's also a dalamud issue technically)

**Comment by Aida-Enna** [comment]
To fully close the issue, we need a ``/xlbgmset 0`` to revert it to the default zone BGM. Thanks, @ff-meli!
